# Generated by Django 3.1.3 on 2020-12-09 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bestellung',
            name='datum',
        ),
    ]
