# Generated by Django 3.1.3 on 2020-12-09 09:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_remove_bestellung_datum'),
    ]

    operations = [
        migrations.AddField(
            model_name='bestellung',
            name='datum',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 12, 9, 10, 36, 33, 574148)),
            preserve_default=False,
        ),
    ]
