# Generated by Django 3.1.1 on 2020-12-14 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_bestellung_datum'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bestellung',
            options={'verbose_name_plural': 'Bestellungen'},
        ),
        migrations.AlterModelOptions(
            name='kunde',
            options={'verbose_name_plural': 'Kunden'},
        ),
    ]
